backend:
  name: git-gateway
  branch: main

# Add this to allow local testing (saves credits!)
local_backend: true

# Vite standard: images in public/images
media_folder: "public/images" 
public_folder: "/images"

site_url: https://rukeykashblog.online

collections:
  - name: "blog"
    label: "Blog Posts"
    # Ensure this folder exists in your project
    folder: "src/data/posts" 
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
