backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/images"
public_folder: "/images"

site_url: https://rukeykashblog.online

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/data/posts"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
